spring.application.name=chapter2
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=Chapter 2 Application
info.app.description=This is a sample Spring Boot application for Chapter 2 of the book.
info.app.version=1.0.0
employee.name=John Doe
spring.security.user.name=neha
spring.security.user.password=zohan
spring.main.lazy-initialization=true
